version: "3.9"

services:
  ollama:
    build: .
    container_name: ollama-qwen3

    ports:
      - "11434:11434"

    volumes:
      - ollama:/root/.ollama

    restart: unless-stopped

volumes:
  ollama: